import { createHash, createPublicKey, verify } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import type { InstallJobPayload, SignedJobEnvelope } from '../shared/api.js'
import { generateSigningKey, privateKeyFromPkcs8, signPayload } from './crypto.js'

type SignedJobFixture = SignedJobEnvelope & {
  clock: string
  deviceId: string
  publicKeySpki: string
}

// Shared with the Android verifier: generated by the real companion signing
// helpers using an ephemeral test key. The fixture contains no private key.
const fixture = JSON.parse(readFileSync(
  new URL('../../../app/src/test/resources/signed-install-job.json', import.meta.url), 'utf8',
)) as SignedJobFixture

describe('companion signed-job protocol', () => {
  it('uses the canonical prefixed 24-hex key ID and verifies the shared fixture signature', () => {
    const spki = Buffer.from(fixture.publicKeySpki, 'base64url')
    const fingerprint = createHash('sha256').update(spki).digest('hex')
    expect(fixture.keyId).toBe('ed25519:' + fingerprint.slice(0, 24))
    expect(fixture.keyId).toMatch(/^ed25519:[0-9a-f]{24}$/)
    const publicKey = createPublicKey({ key: spki, type: 'spki', format: 'der' })
    expect(publicKey.asymmetricKeyType).toBe('ed25519')
    const signature = Buffer.from(fixture.signature, 'base64url')
    expect(signature.byteLength).toBe(64)
    expect(verify(null, Buffer.from(fixture.payload, 'utf8'), publicKey, signature)).toBe(true)
    expect(verify(null, Buffer.from(fixture.payload.replace('Example Bank', 'Other Bank'), 'utf8'), publicKey, signature)).toBe(false)
  })

  it('keeps the cross-language job device-bound and valid at the fixture clock', () => {
    const payload = JSON.parse(fixture.payload) as InstallJobPayload
    expect(payload).toEqual({
      schemaVersion: 1,
      jobId: 'job_1234567890123456',
      deviceId: fixture.deviceId,
      action: 'install_or_update',
      packageName: 'com.example.bank',
      displayName: 'Example Bank',
      acceptedSignerSha256: ['a'.repeat(64)],
      issuedAt: '2026-09-25T17:55:00Z',
      expiresAt: '2026-09-25T18:10:00Z',
      nonce: 'nonce_123456789012',
    })
    expect(Date.parse(payload.issuedAt)).toBeLessThanOrEqual(Date.parse(fixture.clock))
    expect(Date.parse(payload.expiresAt)).toBeGreaterThan(Date.parse(fixture.clock))
    expect(Date.parse(payload.expiresAt) - Date.parse(payload.issuedAt)).toBe(900_000)
    expect(Object.keys(fixture).sort()).toEqual(['clock', 'deviceId', 'keyId', 'payload', 'publicKeySpki', 'signature'])
  })

  it('round-trips real server-generated signing keys and exact payload bytes', () => {
    const key = generateSigningKey()
    const fingerprint = createHash('sha256').update(key.publicKeySpki).digest('hex')
    expect(key.keyId).toBe('ed25519:' + fingerprint.slice(0, 24))
    expect(key.keyId).toMatch(/^ed25519:[0-9a-f]{24}$/)
    const privateKey = privateKeyFromPkcs8(Buffer.from(key.privateKeyPkcs8))
    const signature = signPayload(fixture.payload, privateKey)
    expect(signature).toMatch(/^[A-Za-z0-9_-]{86}$/)
    const publicKey = createPublicKey({ key: key.publicKeySpki, type: 'spki', format: 'der' })
    expect(verify(null, Buffer.from(fixture.payload, 'utf8'), publicKey, Buffer.from(signature, 'base64url'))).toBe(true)
    expect(verify(null, Buffer.from(fixture.payload + '\n', 'utf8'), publicKey, Buffer.from(signature, 'base64url'))).toBe(false)
  })
})
