[tool]
id = "com.gav.borealis"
label = "Borealis"
versionCode = 7
versionName = "0.1.6-alpha.1"
permissions = ["android.permission.INTERNET", "android.permission.ACCESS_NETWORK_STATE", "android.permission.WAKE_LOCK"]
capabilities = ["package-install-request"]
serverPackage = "com.lightos"
orientation = "portrait"
